# Generated by Django 5.1 on 2025-02-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_curatorsgroup_links_statuses_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название группы доступа')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ресское название')),
                ('links', models.ManyToManyField(to='users.links', verbose_name='Доступные страницы')),
                ('possible_actions', models.ManyToManyField(to='users.possibleactions', verbose_name='Возможные действия')),
                ('statuses', models.ManyToManyField(blank=True, to='users.statuses', verbose_name='Доступные статусы')),
            ],
            options={
                'verbose_name': 'Кастомная группа',
                'verbose_name_plural': 'Кастомные группы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.custompermissions'),
        ),
        migrations.AlterField(
            model_name='vocationsschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.custompermissions', verbose_name='группа заместителя'),
        ),
        migrations.DeleteModel(
            name='CustomGroups',
        ),
    ]
