# Generated by Django 5.1 on 2025-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_custompermissions_user_custom_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possibleactions',
            old_name='verbose_name',
            new_name='visible_name',
        ),
        migrations.RemoveField(
            model_name='possibleactions',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='possibleactions',
            name='required_status',
        ),
        migrations.AlterField(
            model_name='custompermissions',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Русское название'),
        ),
    ]
