# Generated by Django 5.1 on 2025-03-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_verbose_name_possibleactions_visible_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='custompermissions',
            name='user_can_view',
            field=models.ManyToManyField(blank=True, related_name='view_statuses', to='users.statuses', verbose_name='Просматриваемые статусы'),
        ),
        migrations.AlterField(
            model_name='custompermissions',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='changed_statuses', to='users.statuses', verbose_name='Изменяемые статусы'),
        ),
    ]
