# Generated by Django 5.1 on 2025-03-19 04:13

import django.utils.timezone
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('justification', models.TextField(verbose_name='Основание')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('one_time', models.BooleanField(default=True, verbose_name='Единовременная закупка')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('union', models.BooleanField(default=False, verbose_name='Объединённый рапорт')),
                ('closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('print_form', models.FileField(blank=True, upload_to=reports.models.report_directory_path)),
                ('sign', models.TextField(blank=True, verbose_name='ЭЦП')),
                ('waiting', models.BooleanField(default=False, verbose_name='Ожидание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорта',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SourcesOfFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник финансирования',
                'verbose_name_plural': 'Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='WaitingStatusForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статус ожидания',
                'verbose_name_plural': 'Статусы ожидания',
            },
        ),
    ]
