# Generated by Django 5.1 on 2025-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-action_date', '-id']},
        ),
    ]
